### ISSUE TITLE
Баг при получении ответа в бинарном задании

### ISSUE THREAD

**Issue by veranikashneidzer** [Shastel/wsc#69]
После того как получаешь ответ с сервера {"name":"binary_arithmetic","task":{"bits":8}} С 8ю битами
и отсылаешь ему код с Uint16Array:
`ws.onmessage = function(data) {
  console.log(data);
  var view = new Uint16Array(data.data);
  {код вычисляющий результат}
  console.log(result);
}`
А затем посылаешь 
ws.send(JSON.stringify({ token: "ххх", command: "binary_arithmetic" }));
То он возвращает 2 сообщения, первое содержит уже 16 бит, а второе масиив с ответом после него, которое можно ввести и закончить задание.

Скрин в приватном репозитории

**Comment by Shastel** [comment]
@VeronikaShneider could you plese link screenshot to this issue?

**Comment by veranikashneidzer** [comment]
![screenshot from 2017-04-06 00-49-31 copy](https://cloud.githubusercontent.com/assets/5623316/24745254/a60fbce0-1abd-11e7-9958-5961c1b68f5c.png)

**Comment by Shastel** [comment]
@humanamburu

**Comment by Shastel** [comment]
@VeronikaShneider i think it works as designed. You requested task twice. @humanamburu could you please take a look on this issue and close if i'm right

**Comment by humanamburu** [comment]
@VeronikaShneider thank you for the report. but @Shastel is right.

Works as expected.
